# docker-compose.production.yml

volumes:
  pg_data_production:
  static_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: ilchukmaxim/taski_backend # Качаем с Docker Hub
    env_file: .env
    volumes:
      - static_volume:/backend_static
  frontend:
    image: ilchukmaxim/taski_frontend  # Качаем с Docker Hub
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static

  gateway:
    image: ilchukmaxim/taski_gateway  # Качаем с Docker Hub
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
    ports:
      - 8000:80